<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_outcome"
 *
 * Auto generated by Extension Builder 2015-04-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'RKW Outcome',
	'description' => '',
	'category' => 'misc',
    'author' => 'Christian Dilger',
    'author_email' => 'c.dilger@addorange.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '8.7.2',
	'constraints' => [
		'depends' => [
            'typo3' => '7.6.0-8.7.99',
            'rkw_basics' => '8.7.80-8.7.99',
            'rkw_events' => '8.7.108-8.7.199',
            'rkw_mailer' => '9.5.11-9.5.99',
            'rkw_registration' => '8.7.41-8.7.99',
            'rkw_shop' => '8.7.26-8.7.99',
            'rkw_survey' => '8.7.69-8.7.99'
		],
		'conflicts' => [
		],
		'suggests' => [
		],
	],
];
