<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_outcome"
 *
 * Auto generated by Extension Builder 2015-04-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'RKW Outcome',
	'description' => '',
	'category' => 'misc',
    'author' => 'Christian Dilger',
    'author_email' => 'c.dilger@addorange.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'clearCacheOnLoad' => 0,
	'version' => '9.5.1002',
	'constraints' => [
		'depends' => [
            'typo3' => '9.5.0-10.4.99',
            'core_extended' => '9.5.0-10.4.99',
            'accelerator' => '9.5.0-10.4.99',
            'fe_register' => '9.5.0-10.4.99',
            'postmaster' => '9.5.0-10.4.99',
            'rkw_events' => '9.5.0-10.4.99',
            'rkw_shop' => '9.5.0-10.4.99',
            'rkw_survey' => '9.5.0-10.4.99'
		],
		'conflicts' => [
		],
		'suggests' => [
		],
	],
];

